# Generated by Django 4.0.4 on 2022-04-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blogs_fileupload_fileword_delete_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='background',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
